version: '3'
services:
  website:
    image: registry.cn-hangzhou.aliyuncs.com/kunlunxu/website:4.2.5 # 镜像地址
    container_name: klx-website # 容器名称
    ports:
      - 3000:3000 # 端口映射
    environment:
      - TZ=Asia/Shanghai # 时区
    logging: # 日志配置
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
