/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */
export * from './extend'

import { api } from '@store/graphql/extend';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Auth: any;
  BillInput: any;
  BodyIndexInput: any;
  Date: any;
  DietInput: any;
  FitnessInput: any;
  Pagination: any;
  Upload: any;
};

export type Algorithm = {
  __typename?: 'Algorithm';
  content?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  id?: Maybe<Scalars['ID']>;
  status?: Maybe<Scalars['Int']>;
  tags?: Maybe<Array<Maybe<Scalars['Int']>>>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type AlgorithmFields = {
  content?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['Int']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
};

export type AlgorithmSearch = {
  content?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Algorithms = {
  __typename?: 'Algorithms';
  change?: Maybe<Array<Maybe<Algorithm>>>;
  list?: Maybe<Array<Maybe<Algorithm>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Article = {
  __typename?: 'Article';
  content?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  name: Scalars['String'];
  status?: Maybe<Scalars['Int']>;
  tags?: Maybe<Array<Datasetsfrom>>;
  thumb?: Maybe<Scalars['String']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
  viewCount?: Maybe<Scalars['Int']>;
  viewHistory?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type ArticleFields = {
  content?: InputMaybe<Scalars['String']>;
  desc?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  tags?: InputMaybe<Array<Scalars['ID']>>;
  thumb?: InputMaybe<Scalars['String']>;
};

export type ArticleSearch = {
  content?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  tag?: InputMaybe<Scalars['ID']>;
  tags?: InputMaybe<Array<Scalars['ID']>>;
  thumb?: InputMaybe<Scalars['String']>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Articles = {
  __typename?: 'Articles';
  change?: Maybe<Array<Maybe<Article>>>;
  list?: Maybe<Array<Maybe<Article>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Bill = {
  __typename?: 'Bill';
  desc?: Maybe<Scalars['String']>;
  expend?: Maybe<Scalars['Float']>;
  income?: Maybe<Scalars['Float']>;
  tag?: Maybe<Scalars['Int']>;
};

export type BodyIndex = {
  __typename?: 'BodyIndex';
  bim?: Maybe<Scalars['Float']>;
  bodyfat?: Maybe<Scalars['Float']>;
  moistureContent?: Maybe<Scalars['Float']>;
  muscle?: Maybe<Scalars['Float']>;
  weight?: Maybe<Scalars['Float']>;
};

export type Datasetsfrom = {
  __typename?: 'Datasetsfrom';
  code?: Maybe<Scalars['Int']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  parent?: Maybe<Datasetsfrom>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
  value?: Maybe<Scalars['Int']>;
};

export type DatasetsfromFields = {
  code?: InputMaybe<Scalars['Int']>;
  desc?: InputMaybe<Scalars['String']>;
  icon?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  parent?: InputMaybe<Scalars['ID']>;
  value?: InputMaybe<Scalars['Int']>;
};

export type DatasetsfromSearch = {
  code?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  icon?: InputMaybe<Scalars['String']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  parent?: InputMaybe<Scalars['ID']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
  value?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
};

export type Datasetsfroms = {
  __typename?: 'Datasetsfroms';
  change?: Maybe<Array<Maybe<Datasetsfrom>>>;
  list?: Maybe<Array<Maybe<Datasetsfrom>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Diaries = {
  __typename?: 'Diaries';
  change?: Maybe<Array<Maybe<Diary>>>;
  list?: Maybe<Array<Maybe<Diary>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Diary = {
  __typename?: 'Diary';
  bill?: Maybe<Array<Maybe<Bill>>>;
  bodyIndex?: Maybe<BodyIndex>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  diet?: Maybe<Array<Maybe<Diet>>>;
  fitness?: Maybe<Array<Maybe<Fitness>>>;
  getUp?: Maybe<Scalars['Date']>;
  id?: Maybe<Scalars['ID']>;
  informalEssay?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  toRest?: Maybe<Scalars['Date']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type DiaryFields = {
  bill?: InputMaybe<Scalars['BillInput']>;
  bodyIndex?: InputMaybe<Scalars['BodyIndexInput']>;
  diet?: InputMaybe<Scalars['DietInput']>;
  fitness?: InputMaybe<Scalars['FitnessInput']>;
  getUp?: InputMaybe<Scalars['Date']>;
  informalEssay?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['Int']>;
  toRest?: InputMaybe<Scalars['Date']>;
};

export type DiarySearch = {
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  names?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
};

export type Diet = {
  __typename?: 'Diet';
  desc?: Maybe<Scalars['String']>;
  type?: Maybe<Scalars['Int']>;
};

export type Fitness = {
  __typename?: 'Fitness';
  place?: Maybe<Scalars['Int']>;
  type?: Maybe<Scalars['Int']>;
};

export type Interview = {
  __typename?: 'Interview';
  content?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  id?: Maybe<Scalars['ID']>;
  status?: Maybe<Scalars['Int']>;
  tags?: Maybe<Array<Maybe<Scalars['Int']>>>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type InterviewFields = {
  content?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['Int']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
};

export type InterviewSearch = {
  content?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Interviews = {
  __typename?: 'Interviews';
  change?: Maybe<Array<Maybe<Interview>>>;
  list?: Maybe<Array<Maybe<Interview>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Kanban = {
  __typename?: 'Kanban';
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type KanbanFields = {
  desc?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
};

export type KanbanGroup = {
  __typename?: 'KanbanGroup';
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  kanban?: Maybe<Kanban>;
  name?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type KanbanGroupFields = {
  desc?: InputMaybe<Scalars['String']>;
  kanban?: InputMaybe<Scalars['ID']>;
  name?: InputMaybe<Scalars['String']>;
};

export type KanbanGroupSearch = {
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  kanban?: InputMaybe<Scalars['ID']>;
  name?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type KanbanGroups = {
  __typename?: 'KanbanGroups';
  change?: Maybe<Array<Maybe<KanbanGroup>>>;
  list?: Maybe<Array<Maybe<KanbanGroup>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type KanbanSearch = {
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type KanbanTask = {
  __typename?: 'KanbanTask';
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  group?: Maybe<KanbanGroup>;
  id?: Maybe<Scalars['ID']>;
  kanban?: Maybe<Kanban>;
  name?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type KanbanTaskFields = {
  desc?: InputMaybe<Scalars['String']>;
  group?: InputMaybe<Scalars['ID']>;
  kanban?: InputMaybe<Scalars['ID']>;
  name?: InputMaybe<Scalars['String']>;
};

export type KanbanTaskSearch = {
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  group?: InputMaybe<Scalars['ID']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  kanban?: InputMaybe<Scalars['ID']>;
  name?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type KanbanTasks = {
  __typename?: 'KanbanTasks';
  change?: Maybe<Array<Maybe<KanbanTask>>>;
  list?: Maybe<Array<Maybe<KanbanTask>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Kanbans = {
  __typename?: 'Kanbans';
  change?: Maybe<Array<Maybe<Kanban>>>;
  list?: Maybe<Array<Maybe<Kanban>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Login = {
  __typename?: 'Login';
  message?: Maybe<Scalars['String']>;
  user?: Maybe<User>;
};

export type MonthlyBill = {
  __typename?: 'MonthlyBill';
  expend?: Maybe<Scalars['Float']>;
  income?: Maybe<Scalars['Float']>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createAlgorithms?: Maybe<Algorithms>;
  createArticles?: Maybe<Articles>;
  createDatasetsfroms?: Maybe<Datasetsfroms>;
  createDiaries?: Maybe<Diaries>;
  createInterviews?: Maybe<Interviews>;
  createKanbanGroups?: Maybe<KanbanGroups>;
  createKanbanTasks?: Maybe<KanbanTasks>;
  createKanbans?: Maybe<Kanbans>;
  createRoles?: Maybe<Roles>;
  createSnippets?: Maybe<Snippets>;
  createTags?: Maybe<Tags>;
  createUsers?: Maybe<Users>;
  login?: Maybe<Login>;
  releaseArticles?: Maybe<Articles>;
  removeAlgorithms?: Maybe<Algorithms>;
  removeArticles?: Maybe<Articles>;
  removeDatasetsfroms?: Maybe<Datasetsfroms>;
  removeDiaries?: Maybe<Diaries>;
  removeInterviews?: Maybe<Interviews>;
  removeKanbanGroups?: Maybe<KanbanGroups>;
  removeKanbanTasks?: Maybe<KanbanTasks>;
  removeKanbans?: Maybe<Kanbans>;
  removePhotos?: Maybe<Photos>;
  removeRoles?: Maybe<Roles>;
  removeSnippets?: Maybe<Snippets>;
  removeTags?: Maybe<Tags>;
  removeUsers?: Maybe<Users>;
  revokeArticles?: Maybe<Articles>;
  updateAlgorithms?: Maybe<Algorithms>;
  updateArticles?: Maybe<Articles>;
  updateDatasetsfroms?: Maybe<Datasetsfroms>;
  updateDiaries?: Maybe<Diaries>;
  updateInterviews?: Maybe<Interviews>;
  updateKanbanGroups?: Maybe<KanbanGroups>;
  updateKanbanTasks?: Maybe<KanbanTasks>;
  updateKanbans?: Maybe<Kanbans>;
  updateRoles?: Maybe<Roles>;
  updateSnippets?: Maybe<Snippets>;
  updateTags?: Maybe<Tags>;
  updateUsers?: Maybe<Users>;
  uploadPhotos?: Maybe<Photos>;
};


export type MutationCreateAlgorithmsArgs = {
  body: Array<AlgorithmFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<AlgorithmSearch>;
};


export type MutationCreateArticlesArgs = {
  body: Array<ArticleFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type MutationCreateDatasetsfromsArgs = {
  body: Array<DatasetsfromFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DatasetsfromSearch>;
};


export type MutationCreateDiariesArgs = {
  body: Array<DiaryFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DiarySearch>;
};


export type MutationCreateInterviewsArgs = {
  body: Array<InterviewFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<InterviewSearch>;
};


export type MutationCreateKanbanGroupsArgs = {
  body: Array<KanbanGroupFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanGroupSearch>;
};


export type MutationCreateKanbanTasksArgs = {
  body: Array<KanbanTaskFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanTaskSearch>;
};


export type MutationCreateKanbansArgs = {
  body: Array<KanbanFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanSearch>;
};


export type MutationCreateRolesArgs = {
  body: Array<RoleFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<RoleSearch>;
};


export type MutationCreateSnippetsArgs = {
  body: Array<SnippetFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<SnippetSearch>;
};


export type MutationCreateTagsArgs = {
  body: Array<TagFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<TagSearch>;
};


export type MutationCreateUsersArgs = {
  body: Array<UserFields>;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<UserSearch>;
};


export type MutationLoginArgs = {
  account?: InputMaybe<Scalars['String']>;
  password?: InputMaybe<Scalars['String']>;
};


export type MutationReleaseArticlesArgs = {
  conds: ArticleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type MutationRemoveAlgorithmsArgs = {
  conds: AlgorithmSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<AlgorithmSearch>;
};


export type MutationRemoveArticlesArgs = {
  conds: ArticleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type MutationRemoveDatasetsfromsArgs = {
  conds: DatasetsfromSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DatasetsfromSearch>;
};


export type MutationRemoveDiariesArgs = {
  conds: DiarySearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DiarySearch>;
};


export type MutationRemoveInterviewsArgs = {
  conds: InterviewSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<InterviewSearch>;
};


export type MutationRemoveKanbanGroupsArgs = {
  conds: KanbanGroupSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanGroupSearch>;
};


export type MutationRemoveKanbanTasksArgs = {
  conds: KanbanTaskSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanTaskSearch>;
};


export type MutationRemoveKanbansArgs = {
  conds: KanbanSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanSearch>;
};


export type MutationRemovePhotosArgs = {
  conds: PhotoSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<PhotoSearch>;
};


export type MutationRemoveRolesArgs = {
  conds: RoleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<RoleSearch>;
};


export type MutationRemoveSnippetsArgs = {
  conds: SnippetSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<SnippetSearch>;
};


export type MutationRemoveTagsArgs = {
  conds: TagSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<TagSearch>;
};


export type MutationRemoveUsersArgs = {
  conds: UserSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<UserSearch>;
};


export type MutationRevokeArticlesArgs = {
  conds: ArticleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type MutationUpdateAlgorithmsArgs = {
  body: AlgorithmFields;
  conds: AlgorithmSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<AlgorithmSearch>;
};


export type MutationUpdateArticlesArgs = {
  body: ArticleFields;
  conds: ArticleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type MutationUpdateDatasetsfromsArgs = {
  body: DatasetsfromFields;
  conds: DatasetsfromSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DatasetsfromSearch>;
};


export type MutationUpdateDiariesArgs = {
  body: DiaryFields;
  conds: DiarySearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DiarySearch>;
};


export type MutationUpdateInterviewsArgs = {
  body: InterviewFields;
  conds: InterviewSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<InterviewSearch>;
};


export type MutationUpdateKanbanGroupsArgs = {
  body: KanbanGroupFields;
  conds: KanbanGroupSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanGroupSearch>;
};


export type MutationUpdateKanbanTasksArgs = {
  body: KanbanTaskFields;
  conds: KanbanTaskSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanTaskSearch>;
};


export type MutationUpdateKanbansArgs = {
  body: KanbanFields;
  conds: KanbanSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanSearch>;
};


export type MutationUpdateRolesArgs = {
  body: RoleFields;
  conds: RoleSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<RoleSearch>;
};


export type MutationUpdateSnippetsArgs = {
  body: SnippetFields;
  conds: SnippetSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<SnippetSearch>;
};


export type MutationUpdateTagsArgs = {
  body: TagFields;
  conds: TagSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<TagSearch>;
};


export type MutationUpdateUsersArgs = {
  body: UserFields;
  conds: UserSearch;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<UserSearch>;
};


export type MutationUploadPhotosArgs = {
  body: PhotoFields;
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<PhotoSearch>;
};

export type Option = {
  __typename?: 'Option';
  id: Scalars['ID'];
  name: Scalars['String'];
};

export type Options = {
  __typename?: 'Options';
  list?: Maybe<Array<Maybe<Option>>>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type OptionsSearch = {
  filter?: InputMaybe<Array<Scalars['ID']>>;
  include?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
};

export type OrderBy = {
  creationTime?: InputMaybe<Scalars['Int']>;
  updateTime?: InputMaybe<Scalars['Int']>;
  value?: InputMaybe<Scalars['Int']>;
  viewCount?: InputMaybe<Scalars['Int']>;
};

export type Photo = {
  __typename?: 'Photo';
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  sourceFileName?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  type?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
  url?: Maybe<Scalars['String']>;
};

export type PhotoFields = {
  files?: InputMaybe<Array<Scalars['Upload']>>;
  payload?: InputMaybe<Scalars['ID']>;
  type?: InputMaybe<Scalars['Int']>;
};

export type PhotoSearch = {
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  sourceFileName?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  type?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
  url?: InputMaybe<Scalars['String']>;
};

export type Photos = {
  __typename?: 'Photos';
  change?: Maybe<Array<Maybe<Photo>>>;
  list?: Maybe<Array<Maybe<Photo>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type PublicKey = {
  __typename?: 'PublicKey';
  data?: Maybe<Scalars['String']>;
  message?: Maybe<Scalars['String']>;
};

export type Query = {
  __typename?: 'Query';
  algorithms?: Maybe<Algorithms>;
  appleTouchbar?: Maybe<Touchbar>;
  articles?: Maybe<Articles>;
  datasetsfroms?: Maybe<Datasetsfroms>;
  diaries?: Maybe<Diaries>;
  interviews?: Maybe<Interviews>;
  kanbanGroups?: Maybe<KanbanGroups>;
  kanbanTasks?: Maybe<KanbanTasks>;
  kanbans?: Maybe<Kanbans>;
  options?: Maybe<Options>;
  photos?: Maybe<Photos>;
  publicKey?: Maybe<PublicKey>;
  roles?: Maybe<Roles>;
  snippets?: Maybe<Snippets>;
  statsBill?: Maybe<StatsBill>;
  tags?: Maybe<Tags>;
  tagsWithArticles?: Maybe<Tags>;
  users?: Maybe<Users>;
};


export type QueryAlgorithmsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<AlgorithmSearch>;
};


export type QueryArticlesArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<ArticleSearch>;
};


export type QueryDatasetsfromsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DatasetsfromSearch>;
};


export type QueryDiariesArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<DiarySearch>;
};


export type QueryInterviewsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<InterviewSearch>;
};


export type QueryKanbanGroupsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanGroupSearch>;
};


export type QueryKanbanTasksArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanTaskSearch>;
};


export type QueryKanbansArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<KanbanSearch>;
};


export type QueryOptionsArgs = {
  model: Scalars['String'];
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<OptionsSearch>;
};


export type QueryPhotosArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<PhotoSearch>;
};


export type QueryRolesArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<RoleSearch>;
};


export type QuerySnippetsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<SnippetSearch>;
};


export type QueryStatsBillArgs = {
  search?: InputMaybe<StatsBillSearch>;
};


export type QueryTagsArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<TagSearch>;
};


export type QueryTagsWithArticlesArgs = {
  orderBy?: InputMaybe<OrderBy>;
  search?: InputMaybe<ArticleSearch>;
};


export type QueryUsersArgs = {
  orderBy?: InputMaybe<OrderBy>;
  pagination?: InputMaybe<Scalars['Pagination']>;
  search?: InputMaybe<UserSearch>;
};

export type Role = {
  __typename?: 'Role';
  auth?: Maybe<Array<Maybe<Scalars['Auth']>>>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  desc?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type RoleFields = {
  auth?: InputMaybe<Array<InputMaybe<Scalars['Auth']>>>;
  desc?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['Int']>;
  type?: InputMaybe<Scalars['Int']>;
};

export type RoleSearch = {
  creator?: InputMaybe<Scalars['ID']>;
  desc?: InputMaybe<Scalars['String']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export enum RoleType {
  Admin = 'ADMIN',
  Tourist = 'TOURIST'
}

export type Roles = {
  __typename?: 'Roles';
  change?: Maybe<Array<Maybe<Role>>>;
  list?: Maybe<Array<Maybe<Role>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Snippet = {
  __typename?: 'Snippet';
  content?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  id?: Maybe<Scalars['ID']>;
  status?: Maybe<Scalars['Int']>;
  tags?: Maybe<Array<Maybe<Scalars['Int']>>>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type SnippetFields = {
  content?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['Int']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
};

export type SnippetSearch = {
  content?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Snippets = {
  __typename?: 'Snippets';
  change?: Maybe<Array<Maybe<Snippet>>>;
  list?: Maybe<Array<Maybe<Snippet>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type StatsBill = {
  __typename?: 'StatsBill';
  groupWithName?: Maybe<Array<Maybe<StatsBillItem>>>;
  message?: Maybe<Scalars['String']>;
  stats?: Maybe<Bill>;
};

export type StatsBillItem = {
  __typename?: 'StatsBillItem';
  diaries?: Maybe<Array<Maybe<Diary>>>;
  expend?: Maybe<Scalars['Float']>;
  income?: Maybe<Scalars['Float']>;
  name?: Maybe<Scalars['String']>;
};

export type StatsBillSearch = {
  name?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
  span?: InputMaybe<Scalars['String']>;
};

export type Tag = {
  __typename?: 'Tag';
  color?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  icon?: Maybe<Scalars['String']>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  parent?: Maybe<Tag>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type TagFields = {
  color?: InputMaybe<Scalars['String']>;
  icon?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  parent?: InputMaybe<Scalars['ID']>;
};

export type TagSearch = {
  color?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  icon?: InputMaybe<Scalars['String']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  parent?: InputMaybe<Scalars['ID']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Tags = {
  __typename?: 'Tags';
  change?: Maybe<Array<Maybe<Tag>>>;
  list?: Maybe<Array<Maybe<Tag>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type Touchbar = {
  __typename?: 'Touchbar';
  latestWeight?: Maybe<Scalars['Float']>;
  monthlyBill?: Maybe<MonthlyBill>;
};

export type User = {
  __typename?: 'User';
  account?: Maybe<Scalars['String']>;
  creationTime?: Maybe<Scalars['Date']>;
  creator?: Maybe<User>;
  id?: Maybe<Scalars['ID']>;
  name?: Maybe<Scalars['String']>;
  role?: Maybe<Role>;
  sex?: Maybe<Scalars['Int']>;
  status?: Maybe<Scalars['Int']>;
  updateTime?: Maybe<Scalars['Date']>;
  updater?: Maybe<User>;
};

export type UserFields = {
  account?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  password?: InputMaybe<Scalars['String']>;
  role?: InputMaybe<Scalars['ID']>;
  sex?: InputMaybe<Scalars['Int']>;
  status?: InputMaybe<Scalars['Int']>;
};

export type UserSearch = {
  account?: InputMaybe<Scalars['String']>;
  creator?: InputMaybe<Scalars['ID']>;
  endCreationTime?: InputMaybe<Scalars['Date']>;
  endUpdateTime?: InputMaybe<Scalars['Date']>;
  id?: InputMaybe<Scalars['ID']>;
  ids?: InputMaybe<Array<Scalars['ID']>>;
  name?: InputMaybe<Scalars['String']>;
  role?: InputMaybe<Scalars['ID']>;
  sex?: InputMaybe<Scalars['Int']>;
  startCreationTime?: InputMaybe<Scalars['Date']>;
  startUpdateTime?: InputMaybe<Scalars['Date']>;
  status?: InputMaybe<Array<InputMaybe<Scalars['Int']>>>;
  updater?: InputMaybe<Scalars['ID']>;
};

export type Users = {
  __typename?: 'Users';
  change?: Maybe<Array<Maybe<User>>>;
  list?: Maybe<Array<Maybe<User>>>;
  message?: Maybe<Scalars['String']>;
  pagination?: Maybe<Scalars['Pagination']>;
};

export type DiaryOutputFieldsFragment = { __typename?: 'Diary', id?: string | null, name?: string | null, getUp?: any | null, toRest?: any | null, informalEssay?: string | null, diet?: Array<{ __typename?: 'Diet', type?: number | null, desc?: string | null } | null> | null, fitness?: Array<{ __typename?: 'Fitness', type?: number | null, place?: number | null } | null> | null, bill?: Array<{ __typename?: 'Bill', tag?: number | null, desc?: string | null, income?: number | null, expend?: number | null } | null> | null, bodyIndex?: { __typename?: 'BodyIndex', bim?: number | null, weight?: number | null, muscle?: number | null, bodyfat?: number | null, moistureContent?: number | null } | null };

export type GetDiariesQueryVariables = Exact<{
  search?: InputMaybe<DiarySearch>;
}>;


export type GetDiariesQuery = { __typename?: 'Query', diaries?: { __typename?: 'Diaries', list?: Array<{ __typename?: 'Diary', id?: string | null, name?: string | null, getUp?: any | null, toRest?: any | null, informalEssay?: string | null, diet?: Array<{ __typename?: 'Diet', type?: number | null, desc?: string | null } | null> | null, fitness?: Array<{ __typename?: 'Fitness', type?: number | null, place?: number | null } | null> | null, bill?: Array<{ __typename?: 'Bill', tag?: number | null, desc?: string | null, income?: number | null, expend?: number | null } | null> | null, bodyIndex?: { __typename?: 'BodyIndex', bim?: number | null, weight?: number | null, muscle?: number | null, bodyfat?: number | null, moistureContent?: number | null } | null } | null> | null } | null };

export type CreateDiariesMutationVariables = Exact<{
  body: Array<DiaryFields> | DiaryFields;
}>;


export type CreateDiariesMutation = { __typename?: 'Mutation', createDiaries?: { __typename?: 'Diaries', change?: Array<{ __typename?: 'Diary', id?: string | null, name?: string | null, getUp?: any | null, toRest?: any | null, informalEssay?: string | null, diet?: Array<{ __typename?: 'Diet', type?: number | null, desc?: string | null } | null> | null, fitness?: Array<{ __typename?: 'Fitness', type?: number | null, place?: number | null } | null> | null, bill?: Array<{ __typename?: 'Bill', tag?: number | null, desc?: string | null, income?: number | null, expend?: number | null } | null> | null, bodyIndex?: { __typename?: 'BodyIndex', bim?: number | null, weight?: number | null, muscle?: number | null, bodyfat?: number | null, moistureContent?: number | null } | null } | null> | null } | null };

export type UpdateDiariesMutationVariables = Exact<{
  body: DiaryFields;
  conds: DiarySearch;
}>;


export type UpdateDiariesMutation = { __typename?: 'Mutation', updateDiaries?: { __typename?: 'Diaries', change?: Array<{ __typename?: 'Diary', id?: string | null, name?: string | null, getUp?: any | null, toRest?: any | null, informalEssay?: string | null, diet?: Array<{ __typename?: 'Diet', type?: number | null, desc?: string | null } | null> | null, fitness?: Array<{ __typename?: 'Fitness', type?: number | null, place?: number | null } | null> | null, bill?: Array<{ __typename?: 'Bill', tag?: number | null, desc?: string | null, income?: number | null, expend?: number | null } | null> | null, bodyIndex?: { __typename?: 'BodyIndex', bim?: number | null, weight?: number | null, muscle?: number | null, bodyfat?: number | null, moistureContent?: number | null } | null } | null> | null } | null };

export type GetStatsBillQueryVariables = Exact<{
  search?: InputMaybe<StatsBillSearch>;
}>;


export type GetStatsBillQuery = { __typename?: 'Query', statsBill?: { __typename?: 'StatsBill', stats?: { __typename?: 'Bill', income?: number | null, expend?: number | null } | null, groupWithName?: Array<{ __typename?: 'StatsBillItem', name?: string | null, income?: number | null, expend?: number | null, diaries?: Array<{ __typename?: 'Diary', name?: string | null, bill?: Array<{ __typename?: 'Bill', desc?: string | null, income?: number | null, expend?: number | null, tag?: number | null } | null> | null } | null> | null } | null> | null } | null };

export type GetStatsBodyIndexQueryVariables = Exact<{
  search?: InputMaybe<DiarySearch>;
}>;


export type GetStatsBodyIndexQuery = { __typename?: 'Query', diaries?: { __typename?: 'Diaries', list?: Array<{ __typename?: 'Diary', name?: string | null, bodyIndex?: { __typename?: 'BodyIndex', weight?: number | null, muscle?: number | null, moistureContent?: number | null, bodyfat?: number | null, bim?: number | null } | null } | null> | null } | null };

export type InitEditorDataQueryVariables = Exact<{ [key: string]: never; }>;


export type InitEditorDataQuery = { __typename?: 'Query', folders?: { __typename?: 'Datasetsfroms', list?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null, parent?: { __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null } | null } | null> | null } | null, articles?: { __typename?: 'Articles', list?: Array<{ __typename?: 'Article', id?: string | null, name: string, thumb?: string | null, status?: number | null, content?: string | null, tags?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, name?: string | null }> | null } | null> | null } | null };

export type CreateFoldersMutationVariables = Exact<{
  body: Array<DatasetsfromFields> | DatasetsfromFields;
}>;


export type CreateFoldersMutation = { __typename?: 'Mutation', createFolders?: { __typename?: 'Datasetsfroms', change?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null, parent?: { __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null } | null } | null> | null } | null };

export type CreateArticlesMutationVariables = Exact<{
  body: Array<ArticleFields> | ArticleFields;
}>;


export type CreateArticlesMutation = { __typename?: 'Mutation', createArticles?: { __typename?: 'Articles', change?: Array<{ __typename?: 'Article', id?: string | null, name: string, tags?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, name?: string | null }> | null } | null> | null } | null };

export type UpdateFoldersMutationVariables = Exact<{
  body: DatasetsfromFields;
  conds: DatasetsfromSearch;
}>;


export type UpdateFoldersMutation = { __typename?: 'Mutation', updateFolders?: { __typename?: 'Datasetsfroms', change?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null, parent?: { __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null } | null } | null> | null } | null };

export type UpdateArticlesMutationVariables = Exact<{
  body: ArticleFields;
  conds: ArticleSearch;
}>;


export type UpdateArticlesMutation = { __typename?: 'Mutation', updateArticles?: { __typename?: 'Articles', change?: Array<{ __typename?: 'Article', id?: string | null, name: string, content?: string | null, thumb?: string | null, status?: number | null, tags?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, name?: string | null }> | null } | null> | null } | null };

export type RemoveArticlesMutationVariables = Exact<{
  conds: ArticleSearch;
}>;


export type RemoveArticlesMutation = { __typename?: 'Mutation', removeArticles?: { __typename?: 'Articles', change?: Array<{ __typename?: 'Article', id?: string | null, name: string } | null> | null } | null };

export type RemoveFoldersMutationVariables = Exact<{
  conds: DatasetsfromSearch;
}>;


export type RemoveFoldersMutation = { __typename?: 'Mutation', removeFolders?: { __typename?: 'Datasetsfroms', change?: Array<{ __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null, parent?: { __typename?: 'Datasetsfrom', id?: string | null, value?: number | null, code?: number | null, desc?: string | null, icon?: string | null, name?: string | null } | null } | null> | null } | null };

export type GetPhotosQueryVariables = Exact<{
  search?: InputMaybe<PhotoSearch>;
}>;


export type GetPhotosQuery = { __typename?: 'Query', photos?: { __typename?: 'Photos', list?: Array<{ __typename?: 'Photo', id?: string | null, type?: number | null, name?: string | null } | null> | null } | null };

export type RemovePhotosMutationVariables = Exact<{
  conds: PhotoSearch;
  search?: InputMaybe<PhotoSearch>;
}>;


export type RemovePhotosMutation = { __typename?: 'Mutation', removePhotos?: { __typename?: 'Photos', change?: Array<{ __typename?: 'Photo', id?: string | null } | null> | null } | null };

export type UploadPhotosMutationVariables = Exact<{
  body: PhotoFields;
}>;


export type UploadPhotosMutation = { __typename?: 'Mutation', uploadPhotos?: { __typename?: 'Photos', change?: Array<{ __typename?: 'Photo', id?: string | null, type?: number | null, name?: string | null } | null> | null } | null };

export type LoginMutationVariables = Exact<{
  account?: InputMaybe<Scalars['String']>;
  password?: InputMaybe<Scalars['String']>;
}>;


export type LoginMutation = { __typename?: 'Mutation', login?: { __typename?: 'Login', message?: string | null, user?: { __typename?: 'User', id?: string | null, sex?: number | null, name?: string | null, status?: number | null, account?: string | null, role?: { __typename?: 'Role', id?: string | null, desc?: string | null, auth?: Array<any | null> | null, name?: string | null } | null } | null } | null };

export type GetPublicKeyQueryVariables = Exact<{ [key: string]: never; }>;


export type GetPublicKeyQuery = { __typename?: 'Query', publicKey?: { __typename?: 'PublicKey', data?: string | null } | null };

export const DiaryOutputFieldsFragmentDoc = `
    fragment DiaryOutputFields on Diary {
  id
  name
  getUp
  toRest
  informalEssay
  diet {
    type
    desc
  }
  fitness {
    type
    place
  }
  bill {
    tag
    desc
    income
    expend
  }
  bodyIndex {
    bim
    weight
    muscle
    bodyfat
    moistureContent
  }
}
    `;
export const GetDiariesDocument = `
    query getDiaries($search: DiarySearch) {
  diaries(search: $search) {
    list {
      ...DiaryOutputFields
    }
  }
}
    ${DiaryOutputFieldsFragmentDoc}`;
export const CreateDiariesDocument = `
    mutation createDiaries($body: [DiaryFields!]!) {
  createDiaries(body: $body) {
    change {
      ...DiaryOutputFields
    }
  }
}
    ${DiaryOutputFieldsFragmentDoc}`;
export const UpdateDiariesDocument = `
    mutation updateDiaries($body: DiaryFields!, $conds: DiarySearch!) {
  updateDiaries(body: $body, conds: $conds) {
    change {
      ...DiaryOutputFields
    }
  }
}
    ${DiaryOutputFieldsFragmentDoc}`;
export const GetStatsBillDocument = `
    query getStatsBill($search: StatsBillSearch) {
  statsBill(search: $search) {
    stats {
      income
      expend
    }
    groupWithName {
      name
      income
      expend
      diaries {
        name
        bill {
          desc
          income
          expend
          tag
        }
      }
    }
  }
}
    `;
export const GetStatsBodyIndexDocument = `
    query getStatsBodyIndex($search: DiarySearch) {
  diaries(search: $search) {
    list {
      name
      bodyIndex {
        weight
        muscle
        moistureContent
        bodyfat
        bim
      }
    }
  }
}
    `;
export const InitEditorDataDocument = `
    query initEditorData {
  folders: datasetsfroms(search: {code: [6]}) {
    list {
      id
      value
      code
      desc
      icon
      name
      parent {
        id
        value
        code
        desc
        icon
        name
      }
    }
  }
  articles {
    list {
      id
      name
      thumb
      status
      content
      tags {
        id
        name
      }
    }
  }
}
    `;
export const CreateFoldersDocument = `
    mutation createFolders($body: [DatasetsfromFields!]!) {
  createFolders: createDatasetsfroms(body: $body) {
    change {
      id
      value
      code
      desc
      icon
      name
      parent {
        id
        value
        code
        desc
        icon
        name
      }
    }
  }
}
    `;
export const CreateArticlesDocument = `
    mutation createArticles($body: [ArticleFields!]!) {
  createArticles(body: $body) {
    change {
      id
      name
      tags {
        id
        name
      }
    }
  }
}
    `;
export const UpdateFoldersDocument = `
    mutation updateFolders($body: DatasetsfromFields!, $conds: DatasetsfromSearch!) {
  updateFolders: updateDatasetsfroms(body: $body, conds: $conds) {
    change {
      id
      value
      code
      desc
      icon
      name
      parent {
        id
        value
        code
        desc
        icon
        name
      }
    }
  }
}
    `;
export const UpdateArticlesDocument = `
    mutation updateArticles($body: ArticleFields!, $conds: ArticleSearch!) {
  updateArticles(body: $body, conds: $conds) {
    change {
      id
      name
      content
      thumb
      status
      tags {
        id
        name
      }
    }
  }
}
    `;
export const RemoveArticlesDocument = `
    mutation removeArticles($conds: ArticleSearch!) {
  removeArticles(conds: $conds) {
    change {
      id
      name
    }
  }
}
    `;
export const RemoveFoldersDocument = `
    mutation removeFolders($conds: DatasetsfromSearch!) {
  removeFolders: removeDatasetsfroms(conds: $conds) {
    change {
      id
      value
      code
      desc
      icon
      name
      parent {
        id
        value
        code
        desc
        icon
        name
      }
    }
  }
}
    `;
export const GetPhotosDocument = `
    query getPhotos($search: PhotoSearch) {
  photos(search: $search) {
    list {
      id
      type
      name
    }
  }
}
    `;
export const RemovePhotosDocument = `
    mutation removePhotos($conds: PhotoSearch!, $search: PhotoSearch) {
  removePhotos(conds: $conds, search: $search, orderBy: {creationTime: -1}) {
    change {
      id
    }
  }
}
    `;
export const UploadPhotosDocument = `
    mutation uploadPhotos($body: PhotoFields!) {
  uploadPhotos(body: $body) {
    change {
      id
      type
      name
    }
  }
}
    `;
export const LoginDocument = `
    mutation login($account: String, $password: String) {
  login(account: $account, password: $password) {
    user {
      id
      sex
      name
      status
      account
      role {
        id
        desc
        auth
        name
      }
    }
    message
  }
}
    `;
export const GetPublicKeyDocument = `
    query getPublicKey {
  publicKey {
    data
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    getDiaries: build.query<GetDiariesQuery, GetDiariesQueryVariables | void>({
      query: (variables) => ({ document: GetDiariesDocument, variables })
    }),
    createDiaries: build.mutation<CreateDiariesMutation, CreateDiariesMutationVariables>({
      query: (variables) => ({ document: CreateDiariesDocument, variables })
    }),
    updateDiaries: build.mutation<UpdateDiariesMutation, UpdateDiariesMutationVariables>({
      query: (variables) => ({ document: UpdateDiariesDocument, variables })
    }),
    getStatsBill: build.query<GetStatsBillQuery, GetStatsBillQueryVariables | void>({
      query: (variables) => ({ document: GetStatsBillDocument, variables })
    }),
    getStatsBodyIndex: build.query<GetStatsBodyIndexQuery, GetStatsBodyIndexQueryVariables | void>({
      query: (variables) => ({ document: GetStatsBodyIndexDocument, variables })
    }),
    initEditorData: build.query<InitEditorDataQuery, InitEditorDataQueryVariables | void>({
      query: (variables) => ({ document: InitEditorDataDocument, variables })
    }),
    createFolders: build.mutation<CreateFoldersMutation, CreateFoldersMutationVariables>({
      query: (variables) => ({ document: CreateFoldersDocument, variables })
    }),
    createArticles: build.mutation<CreateArticlesMutation, CreateArticlesMutationVariables>({
      query: (variables) => ({ document: CreateArticlesDocument, variables })
    }),
    updateFolders: build.mutation<UpdateFoldersMutation, UpdateFoldersMutationVariables>({
      query: (variables) => ({ document: UpdateFoldersDocument, variables })
    }),
    updateArticles: build.mutation<UpdateArticlesMutation, UpdateArticlesMutationVariables>({
      query: (variables) => ({ document: UpdateArticlesDocument, variables })
    }),
    removeArticles: build.mutation<RemoveArticlesMutation, RemoveArticlesMutationVariables>({
      query: (variables) => ({ document: RemoveArticlesDocument, variables })
    }),
    removeFolders: build.mutation<RemoveFoldersMutation, RemoveFoldersMutationVariables>({
      query: (variables) => ({ document: RemoveFoldersDocument, variables })
    }),
    getPhotos: build.query<GetPhotosQuery, GetPhotosQueryVariables | void>({
      query: (variables) => ({ document: GetPhotosDocument, variables })
    }),
    removePhotos: build.mutation<RemovePhotosMutation, RemovePhotosMutationVariables>({
      query: (variables) => ({ document: RemovePhotosDocument, variables })
    }),
    uploadPhotos: build.mutation<UploadPhotosMutation, UploadPhotosMutationVariables>({
      query: (variables) => ({ document: UploadPhotosDocument, variables })
    }),
    login: build.mutation<LoginMutation, LoginMutationVariables | void>({
      query: (variables) => ({ document: LoginDocument, variables })
    }),
    getPublicKey: build.query<GetPublicKeyQuery, GetPublicKeyQueryVariables | void>({
      query: (variables) => ({ document: GetPublicKeyDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useGetDiariesQuery, useLazyGetDiariesQuery, useCreateDiariesMutation, useUpdateDiariesMutation, useGetStatsBillQuery, useLazyGetStatsBillQuery, useGetStatsBodyIndexQuery, useLazyGetStatsBodyIndexQuery, useInitEditorDataQuery, useLazyInitEditorDataQuery, useCreateFoldersMutation, useCreateArticlesMutation, useUpdateFoldersMutation, useUpdateArticlesMutation, useRemoveArticlesMutation, useRemoveFoldersMutation, useGetPhotosQuery, useLazyGetPhotosQuery, useRemovePhotosMutation, useUploadPhotosMutation, useLoginMutation, useGetPublicKeyQuery, useLazyGetPublicKeyQuery } = injectedRtkApi;

