# 基础镜像: 表示在 node 镜像基础上进行扩展, node 镜像中自带 git
FROM node

# 维护者信息: 填写维护者的信息
LABEL moyuanjun moyuanjun@gmai.com

# 安装 pnpm 和 pm2
RUN npm install -g pnpm pm2

# 创建工作目录
RUN mkdir -p /var/website

# 设置 npm home 目录
RUN mkdir -p /var/website/logs/pm2 && chmod -R 777 /var/website
ENV PM2_HOME /var/website/logs/pm2

RUN mkdir -p /root/.config/git /root/.npm/_logs && chmod -R 777 /root

# 设置工作目录
WORKDIR /var/website

# 设置挂载点
VOLUME [/var/website]

# 对外暴露端口
EXPOSE 3000

# 容器启动时执行指令: 指定新建容器在每次运行时需要执行的命令
CMD /bin/bash
