version: '3'
services:
  website:
    image: registry-internal.cn-hangzhou.aliyuncs.com/kunlunxu/website
    container_name: klx-website
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
    logging: # 日志配置
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
